# Generated by Django 5.2.6 on 2025-09-15 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
        ('maintenance', '0002_alter_skill_options_skill_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/photos/', verbose_name='Fotografía'),
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('state', models.BooleanField(default=True, verbose_name='Activo?')),
                ('proficiency_level', models.IntegerField(default=1, verbose_name='Nivel de manejo de habilidad')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='candidate.candidate')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.skill')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ('created_at',),
                'unique_together': {('candidate', 'skill')},
            },
        ),
    ]
