# Generated by Django 5.2.6 on 2025-09-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_remove_candidate_skills_alter_candidate_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='position',
        ),
        migrations.AddField(
            model_name='candidate',
            name='avaliability',
            field=models.CharField(blank=True, null=True, verbose_name='Disponibilidad'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(blank=True, choices=[('Perú', 'Perú'), ('Chile', 'Chile'), ('Ecuador', 'Ecuador')], default=None, max_length=100, null=True, verbose_name='País de procedencia'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Secundaria', 'Secundaria'), ('Tecnico', 'Tecnico'), ('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=255, null=True, verbose_name='Nivel de educación'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_years',
            field=models.CharField(blank=True, default=0, null=True, verbose_name='Años de experiencia'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='has_recommendation',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Recomendación?'),
        ),
    ]
