# Generated by Django 5.2.6 on 2025-09-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_remove_candidate_position_candidate_avaliability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='avaliability',
            field=models.CharField(blank=True, choices=[('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time')], null=True, verbose_name='Disponibilidad'),
        ),
    ]
