# Generated by Django 4.2 on 2025-09-18 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0004_alter_candidate_avaliability'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_candidate', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta del candidato'),
        ),
    ]
