# Generated by Django 4.2 on 2025-09-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_candidate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='birth_date',
            field=models.DateField(help_text='Fecha de nacimiento de candidato', verbose_name='Fecha de nacimiento'),
        ),
    ]
