# Generated by Django 4.2 on 2025-09-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_alter_candidate_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ('-created_at',), 'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
    ]
