# Generated by Django 4.2 on 2025-09-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_alter_candidate_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='avaliability',
            new_name='availability',
        ),
        migrations.AddField(
            model_name='candidate',
            name='certifications_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de certificaciones'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='office_skill_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nivel de herramientas de oficina'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='soft_skills_coverage',
            field=models.PositiveIntegerField(default=0, help_text='Valor de 0 a 100', verbose_name='Cobertura de habilidades blandas (%)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='technical_skills_coverage',
            field=models.PositiveIntegerField(default=0, help_text='Valor de 0 a 100', verbose_name='Cobertura de habilidades técnicas (%)'),
        ),
    ]
