# Generated by Django 4.2 on 2025-09-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_rename_avaliability_candidate_availability_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('created_at',), 'verbose_name': 'Educación', 'verbose_name_plural': 'Educaciones'},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='certifications_count',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='office_skill_level',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='soft_skills_coverage',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='technical_skills_coverage',
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='proficiency_level',
            field=models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado')], default=1, verbose_name='Nivel de manejo de habilidad'),
        ),
    ]
