# Generated by Django 4.2 on 2025-09-29 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0010_certicates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certicates',
            new_name='Certificates',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Bachiller', 'Bachiller'), ('Especialidad', 'Especialidad'), ('Diplomado', 'Diplomado'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=255, null=True, verbose_name='Nivel de educación'),
        ),
    ]
