# Generated by Django 4.2 on 2025-09-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_rename_certicates_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ofimatic',
            field=models.CharField(blank=True, choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado')], default=1, null=True, verbose_name='Conocimientos de ofimática'),
        ),
    ]
