# Generated by Django 4.2 on 2025-10-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_candidate_ofimatic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='ofimatic',
        ),
    ]
