# Generated by Django 4.2 on 2025-10-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_remove_candidate_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento de candidato', null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
