# Generated by Django 4.2 on 2025-10-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_alter_candidate_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='country',
            field=models.CharField(blank=True, choices=[('Perú', 'Perú'), ('Chile', 'Chile'), ('Ecuador', 'Ecuador'), ('Argentina', 'Argentina'), ('España', 'España'), ('Guayaquil', 'Guayaquil'), ('Colombia', 'Colombia'), ('Bolivia', 'Bolivia')], default=None, max_length=100, null=True, verbose_name='País de procedencia'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Bachiller', 'Bachiller'), ('Especialidad', 'Especialidad'), ('Diplomado', 'Diplomado'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado'), ('Licenciado', 'Licenciado'), ('Tecnico', 'Tecnico')], max_length=255, null=True, verbose_name='Nivel de educación'),
        ),
    ]
