# Generated by Django 4.2 on 2025-10-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_alter_candidate_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='experience_years',
            field=models.CharField(blank=True, default=0, null=True, verbose_name='Años de experiencia'),
        ),
    ]
