# Generated by Django 4.2 on 2025-09-20 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Último cambio de contraseña'),
        ),
    ]
