# Generated by Django 5.2.6 on 2025-09-15 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('created_at',), 'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Descripción de Habilidad'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Técnica', 'Técnica'), ('Blanda', 'Blanda'), ('Idioma', 'Language')], default='technical', max_length=20, verbose_name='Categoria de Habilidad'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de Habilidad'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('state', models.BooleanField(default=True, verbose_name='Activo?')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Compañia')),
                ('legal_name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Compañia')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='RUC')),
                ('industry', models.CharField(max_length=20, unique=True, verbose_name='Industria')),
                ('address', models.CharField(max_length=20, unique=True, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Número telefónico')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo electrónico')),
                ('size', models.CharField(choices=[('Pequeña', 'Pequeña'), ('Mediana', 'Mediana'), ('Grande', 'Grande')], max_length=20, verbose_name='Tamao de empresa')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ('created_at',),
            },
        ),
    ]
