# Generated by Django 4.2 on 2025-09-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_skill_options_skill_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de Legal de la Compañia'),
        ),
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(choices=[('Pequeña', 'Pequeña'), ('Mediana', 'Mediana'), ('Grande', 'Grande')], max_length=20, verbose_name='Tamaño de la empresa'),
        ),
    ]
