# Generated by Django 4.2 on 2025-09-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_company_legal_name_alter_company_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Técnica', 'Técnica'), ('Blanda', 'Blanda'), ('Idioma', 'Idioma'), ('Ofimática', 'Ofimática')], default='technical', max_length=20, verbose_name='Categoria de Habilidad'),
        ),
    ]
