# Generated by Django 4.2 on 2025-10-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Técnica', 'Técnica'), ('Blanda', 'Blanda'), ('Idioma', 'Idioma'), ('Ofimática', 'Ofimática')], default='technical', max_length=20, verbose_name='Categoria de Habilidad'),
        ),
    ]
