# Generated by Django 5.2.6 on 2025-09-15 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0002_alter_skill_options_skill_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPositions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('state', models.BooleanField(default=True, verbose_name='Activo?')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de puesto')),
                ('description', models.TextField(verbose_name='Descripción de puesto')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobOffers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('state', models.BooleanField(default=True, verbose_name='Activo?')),
                ('title', models.CharField(max_length=255, verbose_name='Nombre de oferta laboral')),
                ('description', models.TextField(max_length=255, verbose_name='Descripción de oferta')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar')),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modalidad de trabajo')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario mínimo')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario máximo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_joboffers', to='maintenance.company', verbose_name='Posición')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobpositions_joboffers', to='job.jobpositions', verbose_name='Posición')),
            ],
            options={
                'verbose_name': 'Oferta Laboral',
                'verbose_name_plural': 'Ofertas Laborales',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobRequirements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('state', models.BooleanField(default=True, verbose_name='Activo?')),
                ('description', models.CharField(max_length=255, verbose_name='Description de requisitos')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('jobOffers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_joboffert', to='job.joboffers')),
            ],
            options={
                'verbose_name': 'Requisito de puesto',
                'verbose_name_plural': 'Requisitos de puesto',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('state', models.BooleanField(default=True, verbose_name='Activo?')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('jobOffers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_joboffert', to='job.joboffers')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.skill')),
            ],
            options={
                'verbose_name': 'Habilidad para puesto',
                'verbose_name_plural': 'Habilidades para puesto',
                'ordering': ('created_at',),
            },
        ),
    ]
