# Generated by Django 5.2.6 on 2025-09-15 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('maintenance', '0002_alter_skill_options_skill_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.skill', verbose_name='Habilidad'),
        ),
    ]
