# Generated by Django 5.2.6 on 2025-09-15 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_candidate_avaliability'),
        ('job', '0002_alter_jobskill_skill'),
        ('maintenance', '0002_alter_skill_options_skill_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffers',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_joboffers', to='maintenance.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='joboffers',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time')], max_length=50, null=True, verbose_name='Modalidad de trabajo'),
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('state', models.BooleanField(default=True, verbose_name='Activo?')),
                ('status', models.CharField(blank=True, choices=[('Enviado', 'Enviado'), ('En evaluación', 'En evaluación'), ('Procesado', 'Procesado')], max_length=255, null=True, verbose_name='Estado')),
                ('candidte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapplication_candidate', to='candidate.candidate', verbose_name='Candidato')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('joboffers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapplication_joboffers', to='job.joboffers', verbose_name='Oferta laboral')),
            ],
            options={
                'verbose_name': 'Postulacion',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ('created_at',),
            },
        ),
    ]
