# Generated by Django 5.2.6 on 2025-09-16 01:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_joboffers_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicationsAiAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('state', models.BooleanField(default=True, verbose_name='Activo?')),
                ('match_score', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Resultado de evaluación')),
                ('status', models.CharField(blank=True, choices=[('Apto', 'Apto'), ('No apto', 'No apto')], max_length=255, null=True, verbose_name='Resultado de evaluación')),
                ('observation', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('jobApplications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobpositions_joboffers', to='job.jobapplications', verbose_name='Posición')),
            ],
            options={
                'verbose_name': 'Análisis de Postulación',
                'verbose_name_plural': 'Análisis de Postulación',
                'ordering': ('created_at',),
            },
        ),
    ]
