# Generated by Django 5.2.6 on 2025-09-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_aplicationsaianalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffers',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='joboffers',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Activo?'),
        ),
        migrations.AddField(
            model_name='joboffers',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
