# Generated by Django 5.2.6 on 2025-09-16 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_joboffers_end_date_joboffers_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplications',
            old_name='candidte',
            new_name='candidate',
        ),
    ]
