# Generated by Django 5.2.6 on 2025-09-16 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_rename_candidte_jobapplications_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicationsaianalysis',
            name='jobApplications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='job.jobapplications', verbose_name='Posición'),
        ),
    ]
