# Generated by Django 5.2.6 on 2025-09-21 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_aplicationsaianalysis_jobapplications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffers',
            name='is_urgent',
            field=models.BooleanField(blank=True, null=True, verbose_name='Es uregente?'),
        ),
        migrations.AddField(
            model_name='joboffers',
            name='mode',
            field=models.CharField(blank=True, choices=[('Remoto', 'Remoto'), ('Presencial', 'Presencial'), ('Híbrido', 'Híbrido')], max_length=50, null=True, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='joboffers',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time')], max_length=50, null=True, verbose_name='Tipo de trabajo'),
        ),
        migrations.CreateModel(
            name='JobBenefits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('state', models.BooleanField(default=True, verbose_name='Activo?')),
                ('description', models.CharField(max_length=255, verbose_name='Description de requisitos')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('jobOffers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits_joboffert', to='job.joboffers')),
            ],
            options={
                'verbose_name': 'Beneficio de puesto',
                'verbose_name_plural': 'Beneficios de puesto',
                'ordering': ('created_at',),
            },
        ),
    ]
