# Generated by Django 5.2.6 on 2025-09-21 17:44

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_joboffers_is_urgent_joboffers_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='candidate_snapshot',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Datos del candidato al momento de la postulación'),
        ),
    ]
