# Generated by Django 5.2.6 on 2025-09-21 17:52

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_jobapplications_candidate_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='has_snapshot',
            field=models.BooleanField(default=False, editable=False, verbose_name='Información del usuario almacenada'),
        ),
        migrations.AlterField(
            model_name='jobapplications',
            name='candidate_snapshot',
            field=models.JSONField(blank=True, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Datos del candidato al momento de la postulación'),
        ),
    ]
