# Generated by Django 4.2 on 2025-09-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_jobapplications_has_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='has_snapshot',
            field=models.BooleanField(default=False, verbose_name='Información del usuario almacenada'),
        ),
    ]
