# Generated by Django 4.2 on 2025-09-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_alter_jobapplications_has_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobbenefits',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description de beneficios'),
        ),
    ]
