# Generated by Django 4.2 on 2025-09-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_jobbenefits_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicationsaianalysis',
            name='status',
            field=models.CharField(blank=True, choices=[('Desconocido', 'Desconocido'), ('No contratado', 'No contratado'), ('Contratado', 'Contratado'), ('Rechazado', 'Rechazado'), ('Aprobado', 'Aprobado'), ('Evaluado', 'Evaluado'), ('En evaluación', 'En evaluación')], max_length=255, null=True, verbose_name='Resultado de evaluación'),
        ),
    ]
