# Generated by Django 4.2 on 2025-10-03 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0013_alter_aplicationsaianalysis_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsAiAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('state', models.BooleanField(default=True, verbose_name='Activo?')),
                ('job_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('semantic_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('structural_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fairness_structural_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fairness_overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fairness_overall_delta', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('structural_breakdown', models.JSONField(blank=True, null=True)),
                ('fairness_groups', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Desconocido', 'Desconocido'), ('No contratado', 'No contratado'), ('Contratado', 'Contratado'), ('Rechazado', 'Rechazado'), ('Aprobado', 'Aprobado'), ('Evaluado', 'Evaluado'), ('En evaluación', 'En evaluación')], max_length=255, null=True, verbose_name='Resultado')),
                ('observation', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('jobApplications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='job.jobapplications', verbose_name='Postulación')),
            ],
            options={
                'verbose_name': 'Análisis de Postulación',
                'verbose_name_plural': 'Análisis de Postulaciones',
                'ordering': ('created_at',),
            },
        ),
        migrations.DeleteModel(
            name='AplicationsAiAnalysis',
        ),
    ]
