# Generated by Django 4.2 on 2025-10-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_applicationsaianalysis_delete_aplicationsaianalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsaianalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registrado el'),
        ),
        migrations.AlterField(
            model_name='applicationsaianalysis',
            name='status',
            field=models.CharField(blank=True, choices=[('Desconocido', 'Desconocido'), ('No contratado', 'No contratado'), ('Contratado', 'Contratado'), ('Rechazado', 'Rechazado'), ('Aprobado', 'Aprobado'), ('Evaluado', 'Evaluado'), ('En evaluación', 'En evaluación')], default='En evaluación', max_length=255, null=True, verbose_name='Resultado'),
        ),
    ]
