# Generated by Django 4.2 on 2025-10-11 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_applicationsaianalysis_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Identificador de la ejecución')),
                ('candidate_count', models.PositiveIntegerField(default=0, verbose_name='CVs procesados')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de la evaluación')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la evaluación')),
                ('processing_time_seconds', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tiempo total (s)')),
                ('processing_time_per_candidate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tiempo promedio por CV (s)')),
                ('candidate_processing_times', models.JSONField(blank=True, help_text='Lista de objetos {id, name, processing_time_seconds}', null=True, verbose_name='Duración por CV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_application_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_metrics', to='job.jobapplications', verbose_name='Postulación / Lote')),
            ],
            options={
                'verbose_name': 'Métrica de tiempo',
                'verbose_name_plural': 'Métricas de tiempo',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='applicationsaianalysis',
            name='time_metrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.timemetrics'),
        ),
    ]
