# Generated by Django 4.2 on 2025-10-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_timemetrics_applicationsaianalysis_time_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsaianalysis',
            name='time_metrics',
        ),
        migrations.AddField(
            model_name='applicationsaianalysis',
            name='processing_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de fin de evaluación'),
        ),
        migrations.AddField(
            model_name='applicationsaianalysis',
            name='processing_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio de evaluación'),
        ),
        migrations.AddField(
            model_name='applicationsaianalysis',
            name='processing_time_seconds',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Duración de evaluación (segundos)'),
        ),
    ]
