# Generated by Django 4.2 on 2025-10-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_remove_applicationsaianalysis_time_metrics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsaianalysis',
            name='processing_time_seconds',
        ),
        migrations.AddField(
            model_name='applicationsaianalysis',
            name='processing_time_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Duración de evaluación (minutos)'),
        ),
    ]
