# Generated by Django 4.2 on 2025-10-11 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_remove_applicationsaianalysis_processing_time_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('criterio', models.CharField(max_length=100)),
                ('grupo_protegido', models.CharField(max_length=100)),
                ('total_cvs_gp', models.PositiveIntegerField()),
                ('cvs_preseleccionados_gp', models.PositiveIntegerField()),
                ('tasa_seleccion_gp', models.FloatField()),
                ('grupo_referente', models.CharField(max_length=100)),
                ('total_cvs_gr', models.PositiveIntegerField()),
                ('cvs_preseleccionados_gr', models.PositiveIntegerField()),
                ('tasa_seleccion_gr', models.FloatField()),
                ('spd', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_summaries', to='job.joboffers')),
            ],
            options={
                'verbose_name': 'Resumen de selección',
                'verbose_name_plural': 'Resumenes de selección',
            },
        ),
    ]
