# Generated by Django 4.2 on 2025-10-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_evaluationsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsaianalysis',
            name='processing_time_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Duración de evaluación (segundos)'),
        ),
        migrations.AlterField(
            model_name='joboffers',
            name='description',
            field=models.TextField(verbose_name='Descripción de oferta'),
        ),
    ]
