# Generated by Django 4.2 on 2025-10-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_alter_applicationsaianalysis_processing_time_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='status_interview',
            field=models.CharField(blank=True, choices=[('Contratado', 'Contratado'), ('Pasa entrevista', 'Pasa entrevista'), ('No pasa entrevista', 'No pasa entrevista')], max_length=255, null=True, verbose_name='Estado de la entrevista'),
        ),
    ]
