# Generated by Django 4.2 on 2025-10-14 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_jobapplications_status_interview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de evaluación')),
                ('total_cvs', models.PositiveIntegerField(default=0, verbose_name='N° CVs evaluados')),
                ('total_cvs_selected', models.PositiveIntegerField(default=0, verbose_name='N° CVs seleccionados (IA o reclutador)')),
                ('total_cvs_passed_ef', models.PositiveIntegerField(default=0, verbose_name='N° CVs que pasan a entrevista final (EF)')),
                ('selection_accuracy', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Exactitud de selección (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_applications', models.ManyToManyField(blank=True, related_name='accuracy_metrics', to='job.jobapplications', verbose_name='Postulaciones del día')),
            ],
            options={
                'verbose_name': 'Exactitud de Selección',
                'verbose_name_plural': 'Exactitudes de Selección',
                'ordering': ['-interview_date'],
            },
        ),
    ]
